# Generated by Django 6.0.4 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course_name',
            field=models.CharField(choices=[('1', 'Appetizers'), ('2', 'Main Course'), ('3', 'Dessert')], max_length=20),
        ),
    ]
